// Generated by Haxe 4.1.3
(function ($global) { "use strict";
var Main = function() { };
Main.main = function() {
	window.onload = function() {
		var _g = 0;
		var _g1 = window.document.getElementsByClassName("imglink");
		while(_g < _g1.length) {
			var element = [_g1[_g]];
			++_g;
			element[0].onmouseover = (function(element) {
				return function() {
					element[0].className = "overed";
				};
			})(element);
			element[0].onmouseout = (function(element) {
				return function() {
					element[0].className = "imglink";
				};
			})(element);
		}
	};
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
Main.main();
})({});
